-- --------------------------------------------------------
-- Sunucu:                       127.0.0.1
-- Sunucu sürümü:                10.4.18-MariaDB - mariadb.org binary distribution
-- Sunucu İşletim Sistemi:       Win64
-- HeidiSQL Sürüm:               11.2.0.6213
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


-- es_extended için veritabanı yapısı dökülüyor
CREATE DATABASE IF NOT EXISTS `es_extended` /*!40100 DEFAULT CHARACTER SET utf8mb4 */;
USE `es_extended`;

-- tablo yapısı dökülüyor es_extended.motels
CREATE TABLE IF NOT EXISTS `motels` (
  `id` varchar(255) COLLATE utf8mb4_bin NOT NULL DEFAULT '[]',
  `data` longtext COLLATE utf8mb4_bin DEFAULT NULL,
  `identifier` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `bought` tinyint(255) DEFAULT 0,
  `boughtDate` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  `keyData` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin ROW_FORMAT=DYNAMIC;

-- es_extended.motels: ~242 rows (yaklaşık) tablosu için veriler indiriliyor
/*!40000 ALTER TABLE `motels` DISABLE KEYS */;
INSERT INTO `motels` (`id`, `data`, `identifier`, `bought`, `boughtDate`, `keyData`) VALUES
	('1_1', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('1_2', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('1_4', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('1_3', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('1_6', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('1_5', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('1_7', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('1_8', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('1_9', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('1_10', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('1_11', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('1_12', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('1_13', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('1_14', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('1_15', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('1_17', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('1_18', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('1_16', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('1_20', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('1_19', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('1_21', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('1_22', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_1', '{"stash":{"lock":true},"door":{"lock":false}}', NULL, 0, NULL, NULL),
	('1_23', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_2', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_3', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_4', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_5', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_6', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_7', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_8', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_9', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_10', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_11', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_12', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_13', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_14', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_15', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_16', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_17', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_18', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_19', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_20', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_21', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_22', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_23', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_24', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_25', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_26', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_27', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_28', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_29', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_30', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_31', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_32', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_33', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_34', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_35', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_36', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_37', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_38', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_39', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_40', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_41', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_42', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_43', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_44', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_45', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_46', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_47', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_48', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_49', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_50', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_51', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_52', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_53', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_54', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_55', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_56', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_57', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_59', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_60', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_61', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_62', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_63', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_58', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_64', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_65', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_67', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_66', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_69', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_70', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_71', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_72', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_68', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_73', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_74', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_76', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_75', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_78', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_79', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_77', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_80', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_81', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_84', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_85', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_82', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_83', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_87', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_88', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_86', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_90', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_91', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_89', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('1_1', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('1_2', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('1_3', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('1_4', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('1_7', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('1_5', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('1_6', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('1_8', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('1_10', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('1_9', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('1_11', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('1_12', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('1_14', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('1_13', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('1_16', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('1_15', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('1_19', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('1_20', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('1_17', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('1_18', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('1_21', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('1_22', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('1_23', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_2', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_1', '{"stash":{"lock":true},"door":{"lock":false}}', NULL, 0, NULL, NULL),
	('2_4', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_3', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_6', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_5', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_7', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_8', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_9', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_11', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_10', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_12', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_13', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_14', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_16', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_15', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_17', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_18', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_20', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_19', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_21', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_22', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_24', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_25', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_26', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_23', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_28', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_30', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_27', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_29', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_31', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_33', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_34', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_35', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_32', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_36', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_37', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_38', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_39', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_40', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_41', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_42', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_43', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_44', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_45', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_46', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_48', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_49', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_50', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_47', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_53', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_51', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_52', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_54', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_55', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_56', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_57', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_58', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_59', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_60', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_61', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_64', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_65', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_62', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_63', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_66', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_68', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_69', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_70', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_67', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_71', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_72', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_75', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_73', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_74', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_78', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_79', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_81', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_76', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_77', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_80', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_82', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_83', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_86', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_84', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_85', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_87', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_88', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_89', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_90', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('2_91', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('3_1', '{"stash":{"lock":true},"door":{"lock":true}}', 'steam:1100001129c58ab', 1, 'Wed May 19 21:45:33 2021', 'kcPhsNjrwevaXQQ'),
	('3_2', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('3_5', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('3_6', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('3_3', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('3_4', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('3_7', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('3_9', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('3_8', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('3_10', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('3_11', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('3_12', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('3_13', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL),
	('3_14', '{"stash":{"lock":true},"door":{"lock":true}}', NULL, 0, NULL, NULL);
/*!40000 ALTER TABLE `motels` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
